SET session_replication_role = replica;
DELETE FROM product CASCADE;
DELETE FROM amazon_category CASCADE;
DELETE FROM amazon_cart CASCADE;
DELETE FROM Inventory CASCADE;
DELETE FROM "order";
DELETE FROM Warehouse CASCADE;

INSERT INTO Product(id,title,description,price,img,sales) VALUES (1,'Vacuum Insulated Tumbler','Stanley Quencher H2.0 FlowState Stainless Steel Vacuum Insulated Tumbler with Lid and Straw for Water, Iced Tea or Coffee, Smoothie and More',45,'/static/img/1.jpg',20);
INSERT INTO Product(id,title,description,price,img,sales) VALUES (2,'Logitech Pebble Wireless Mouse','Logitech Pebble Wireless Mouse with Bluetooth or 2.4 GHz Receiver, Silent, Slim Computer Mouse with Quiet Clicks, for Laptop/Notebook/iPad/PC/Mac/Chromebook - Pink Rose',23.99,'/static/img/2.jpg',40);
INSERT INTO Product(id,title,description,price,img,sales) VALUES (3,'OMOTON Tablet Stand','OMOTON Tablet Stand Holder Adjustable, T1 Desktop Aluminum Tablet Dock Cradle Compatible with iPad Air/Mini, iPad 10.2/9.7, iPad Pro 11/12.9, Samsung Tab and More, Rose Gold',15.99,'/static/img/3.jpg',22);
INSERT INTO Product(id,title,description,price,img,sales) VALUES (4,'PU Leather Keyboard','PU Leather Keyboard Sleeve Case for Logitech K380 Wireless Bluetooth Multi-Device Keyboard, Logitech K380 Mac Windows Chrome OS Keyboard Cover Skin Protector-Pink',34.99,'/static/img/4.jpg',24);
INSERT INTO Product(id,title,description,price,img,sales) VALUES (5,'Polycom Phone Headset','Polycom Phone Headset Noise Cancelling Mic RJ9 U10P Bottom Cable Compatible with Polycom VVX, Shoretel, Avaya Digital Phones',16.78,'/static/img/5.jpg',23);
INSERT INTO Product(id,title,description,price,img,sales) VALUES (6,'Magic Keyboard','Magic Keyboard for iPad Pro 12.9, iPad 12.9 Pro Case with Keyboard 6th, 5th, 4th, 3rd Generation (2022/2021/2020/2018), 360 Swivel & Multi-Touch Trackpad, Backlit, 12.9 Ultra Thin Keyboard Case, Black',139.99,'/static/img/6.jpg',400);
INSERT INTO Product(id,title,description,price,img,sales) VALUES (7,'BIGalleons Mobile TV Mount Stand','BIGalleons Mobile TV Mount Stand, Low Height Monitor Cart with Wheels for 32-65 inch Flat Curved Screen TV, LED LCD, Height Adjustable, 90°Adjustable Viewing Angle',239.89,'/static/img/7.jpg',50);
INSERT INTO Product(id,title,description,price,img,sales) VALUES (8,'Mobile TV','Rolling/Mobile TV Cart with Wheels for 32-75 Inch LCD LED 4K Flat Screen TVs - TV Floor Stand with Shelf Holds Up to 100 lbs, Height Adjustable Trolley Max VESA 600x400mm- PSTVMC05',149.97,'/static/img/8.jpg',59);
INSERT INTO Product(id,title,description,price,img,sales) VALUES ( 9,'HPC Optics','HPC Optics Compatible with Mellanox MFA1A00-C002 100G QSFP28 to QSFP28 2m Active Optical Cable',299.69,'/static/img/9.jpg',30);
INSERT INTO Product(id,title,description,price,img,sales) VALUES ( 10,'Laptop Stand','Lamicall Adjustable Laptop Stand, Portable Laptop Riser, Aluminum Laptop Stand for Desk Foldable, Ergonomic Computer Notebook Stand Holder for MacBook Air Pro, Dell XPS, HP (10-17.3'''') - Silver',1,'/static/img/10.jpg',40);
INSERT INTO Product(id,title,description,price,img,sales) VALUES ( 11,'AUTOMET','AUTOMET Womens 2 in 1 Flowy Butterfly Running Athletic Workout Trendy Shorts Summer Casual High Waisted Yoga Tennis Skirts',18.99,'/static/img/11.jpg',2);
INSERT INTO Product(id,title,description,price,img,sales) VALUES ( 12,'Ezymall','Ezymall Womens 2 in 1 Flowy Shorts Casual Summer Athletic Running Workout Shorts High Waisted Biker Gym Yoga Tennis Skirts',23.99,'/static/img/12.jpg',0);
INSERT INTO Product(id,title,description,price,img,sales) VALUES ( 13,'OQQ','OQQ Women''s 3 Piece Medium Support Crop Top Seamless Ribbed Removable Cups Workout Yoga Sport Bra',36.99,'/static/img/13.jpg',1);
INSERT INTO Product(id,title,description,price,img,sales) VALUES ( 14,'LILLUSORY','LILLUSORY 2 Piece Outfits For Women Trendy Lounge Sets Cozy Knit Sweater Short Sleeve Fashion Loungewear Set',48.99,'/static/img/14.jpg',0);
INSERT INTO Product(id,title,description,price,img,sales) VALUES ( 15,'EFAN','EFAN Womens Oversized Half Zip Pullover Long Sleeve Sweatshirt Quarter Zip Trendy Hoodie Ouffits Teen Girls Fall Y2K Clothes',34.99,'/static/img/15.jpg',0);
INSERT INTO Product(id,title,description,price,img,sales) VALUES ( 16,'Dokotoo','Dokotoo Womens Summer Tops Crewneck Lace Crochet Short Sleeve Shirts Casual Chiffon Blouses',26.99,'/static/img/16.jpg',1);
INSERT INTO Product(id,title,description,price,img,sales) VALUES ( 17,'Dokotoo','Dokotoo Womens Blouses and Tops Short Sleeve Chiffon Shirts and Tops',27.99,'/static/img/17.jpg',0);
INSERT INTO Product(id,title,description,price,img,sales) VALUES ( 18,'Amazon Essentials','Amazon Essentials Men''s Tech Stretch Long-Sleeve T-Shirt',13.52,'/static/img/18.jpg',1);
INSERT INTO Product(id,title,description,price,img,sales) VALUES ( 19,'AUTOMET','AUTOMET Womens 2 Piece Outfits Lounge Matching Sets Two Piece Linen Shorts Crop Tops 2023 Trendy Clothes Summer Vacation Set',36.99,'/static/img/19.jpg',0);
INSERT INTO Product(id,title,description,price,img,sales) VALUES ( 20,'Lancôme Makeup Primer','Lancôme La Base Pro Makeup Primer - Perfecting & Smoothing Makeup Base - Oil-free - 0.8 Fl Oz',34.99,'/static/img/20.jpg',1);
INSERT INTO Product(id,title,description,price,img,sales) VALUES ( 21,'Skinperfect Primer SPF30','Dermalogica Skinperfect Primer SPF30, Anti-Aging Makeup Primer with Broad Spectrum Sunscreen - Brighten and Prime For Flawless Skin, 0.75 Fl Oz (Pack of 1)
0.75 Fl Oz (Pack of 1)',56.7,'/static/img/21.jpg',0);
INSERT INTO Product(id,title,description,price,img,sales) VALUES ( 22,'Makeup Foundation','[VINNE] Essential Radiance Skin Nuder Cushion Makeup Foundation Daily Sunscreen UV Protection SPF50+ PA++++ Broad Spectrum For Beauty Sensitive Skin and Acne skin - Refill not Included (#21 Light Beige)',29.89,'/static/img/22.jpg',0);
INSERT INTO Product(id,title,description,price,img,sales) VALUES ( 23,'Makeup Mirror','YUVIKE Travel Makeup Mirror, Vanity Mirror with Lights, Rechargeable Travel Vanity Mirror,Portable Ultra Slim Lighted Makeup Mirror, Travel Essential for Women',19.99,'/static/img/23.jpg',0);
INSERT INTO Product(id,title,description,price,img,sales) VALUES ( 24,'Lip Pencil','NYX PROFESSIONAL MAKEUP Slim Lip Pencil, Peakaboo Neutral',4.97,'/static/img/24.jpg',0);
INSERT INTO Product(id,title,description,price,img,sales) VALUES ( 25,'Plumping Lip Oil','Sea-Maid Plumping Lip Oil, Hydrating Gloss Tinted Lip Balm Transparent Lip Care, Big Brush Head Glitter Shine, Long Lasting Nourishing Non-sticky Fresh Texture',8.99,'/static/img/25.jpg',0);
INSERT INTO Product(id,title,description,price,img,sales) VALUES ( 26,'Lash Enhancer','TEQUILA COSMETICS H2O LASH FORMULA | RX LASH ENHANCING - Conditioning Lash Enhancer Serum for Longer and Thicker lashes, 1 Fl Oz',74.89,'/static/img/26.jpg',0);
INSERT INTO amazon_category VALUES (1,'Electronic Product',3);
INSERT INTO amazon_category VALUES (2,'Electronic Product',1);
INSERT INTO amazon_category VALUES (3,'Electronic Product',7);
INSERT INTO amazon_category VALUES (4,'Electronic Product',8);
INSERT INTO amazon_category VALUES (5,'Electronic Product',10);
INSERT INTO amazon_category VALUES (6,'Electronic Product',5);
INSERT INTO amazon_category VALUES (7,'Electronic Product',6);
INSERT INTO amazon_category VALUES (8,'Electronic Product',4);
INSERT INTO amazon_category VALUES (9,'Electronic Product',2);
INSERT INTO amazon_category VALUES (10,'Electronic Product',9);
INSERT INTO amazon_category VALUES (11,'Clothes',16);
INSERT INTO amazon_category VALUES (12,'Clothes',17);
INSERT INTO amazon_category VALUES (13,'Clothes',18);
INSERT INTO amazon_category VALUES (14,'Clothes',19);
INSERT INTO amazon_category VALUES (15,'Clothes',11);
INSERT INTO amazon_category VALUES (16,'Clothes',13);
INSERT INTO amazon_category VALUES (17,'Clothes',12);
INSERT INTO amazon_category VALUES (18,'Clothes',14);
INSERT INTO amazon_category VALUES (19,'Clothes',15);
INSERT INTO amazon_category VALUES (20,'Make Up',20);
INSERT INTO amazon_category VALUES (21,'Make Up',21);
INSERT INTO amazon_category VALUES (22,'Make Up',22);
INSERT INTO amazon_category VALUES (23,'Make Up',23);
INSERT INTO amazon_category VALUES (24,'Make Up',24);
INSERT INTO amazon_category VALUES (25,'Make Up',25);
INSERT INTO amazon_category VALUES (26,'Make Up',26);
