# Generated by Django 4.1.5 on 2023-04-28 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0003_alter_inventory_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazonuser',
            name='ups_account',
            field=models.TextField(blank=True),
        ),
    ]
