version: '2'

services:
  db:
      image: postgres
      environment:
        - POSTGRES_DB=amazon_568
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=passw0rd
      restart: always
      expose:
        - "5432"

      # volumes:
      #   - data-volume:/var/lib/postgresql/data
  web-init:
      build: ./mini-amazon
      command: /code/initweb.sh
      volumes:
        - ./mini-amazon:/code
      depends_on:
        - db
  web:
      build: ./mini-amazon
      user: nobody
      command: /code/runweb.sh
      volumes:
        - ./mini-amazon:/code
      depends_on:
        - web-init
  amazon-server:
      build: ./mini-amazon
      command: /code/runamazon.sh
      volumes:
        - ./mini-amazon:/code
      depends_on:
        - web-init
  nginx:
     image: nginx:latest
     ports:
       - "8000:8000"
     volumes:
       - ./nginx/config:/etc/nginx/conf.d
     depends_on:
       - web-init
volumes:
   data-volume: 
